osx_image: xcode10.2  
language: swift

before_install:
- pod install --repo-update

script:
- xcodebuild test -workspace ChatooRx.xcworkspace -scheme ChatooRx -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c

after_success:
- bash <(curl -s https://codecov.io/bash)
