cat codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
    notify:
        require_ci_to_pass: yes
    comment:
        layout: "header, changes, diff, sunburst"


    coverage:
        ignore:
            - Pods/.*
            - Applications/Xcode.app/.*
            - vendor/.*
            - Carthage/.*

    status:
        project: yes
        patch: yes
        changes: no
